### ISSUE TITLE
 download address for super-resolution-10.onnx

### ISSUE THREAD

**Issue by gaoxumustwin** [marty1885/rknn-superresolution#2]
Hello author, I'm sorry but the download address for super-resolution-10.onnx is no longer valid. Do you have a new download connection on your end?

**Comment by marty1885** [comment]
Hi, I've updated the link. It should work now.

Here's it is for reference.
https://github.com/onnx/models/blob/bec48b6a70e5e9042c0badbaafefe4454e072d08/validated/vision/super_resolution/sub_pixel_cnn_2016/model/super-resolution-10.onnx

**Comment by gaoxumustwin** [comment]
Thank you for your recovery
